#!/bin/bash

DOTFILES=$(cd $(dirname "${BASH_SOURCE[0]}") && pwd)

rm -rf $HOME/.config/nvim
ln -s $DOTFILES/nvim $HOME/.config/nvim

rm -rf $HOME/.config/kitty
ln -s $DOTFILES/kitty $HOME/.config/kitty

rm -rf $HOME/.tmux.conf
rm -rf $HOME/.tmux/plugins
ln -s $DOTFILES/tmux/tmux.conf $HOME/.tmux.conf
ln -s $DOTFILES/tmux/plugins $HOME/.tmux/plugins

mkdir -p $HOME/.local/bin
rm -rf $HOME/.local/bin/ts
ln -s $DOTFILES/scripts/ts $HOME/.local/bin/ts

rm -rf $HOME/.aliases
ln -s $DOTFILES/.aliases $HOME/.aliases

rm -rf $HOME/.config/phpactor
ln -s $DOTFILES/phpactor $HOME/.config/phpactor
