#!/bin/zsh

DOTFILES="$(cd "$(dirname "$0")" && pwd)"
COMPLETION_DIR="$HOME/.oh-my-zsh/completions"

mkdir -p "$COMPLETION_DIR"

# Add to fpath only if not already present
typeset -U fpath
if [[ ! "$fpath"[(r)$COMPLETION_DIR] ]]; then
  fpath=("$COMPLETION_DIR" $fpath)
fi

# Neovim config
rm -rf "$HOME/.config/nvim"
ln -s "$DOTFILES/nvim" "$HOME/.config/nvim"

# Kitty config
rm -rf "$HOME/.config/kitty"
ln -s "$DOTFILES/kitty" "$HOME/.config/kitty"

# Tmux config
rm -rf "$HOME/.tmux.conf" "$HOME/.tmux/plugins"
ln -s "$DOTFILES/tmux/tmux.conf" "$HOME/.tmux.conf"
ln -s "$DOTFILES/tmux/plugins" "$HOME/.tmux/plugins"

# mycli config
rm -rf "$HOME/.myclirc"
ln -s "$DOTFILES/mycli/.myclirc" "$HOME/.myclirc"

# aider config
rm -rf "$HOME/.aider.conf.yml"
rm -rf "$HOME/.aider.model.settings.yml"
ln -s "$DOTFILES/aider/config.yml" "$HOME/.aider.conf.yml"
ln -s "$DOTFILES/aider/config.yml" "$HOME/.aider.model.settings.yml"

# Local scripts
mkdir -p "$HOME/.local/bin"

rm -rf "$HOME/.local/bin/ts"
ln -s "$DOTFILES/scripts/ts" "$HOME/.local/bin/ts"

rm -rf "$HOME/.local/bin/invoice"
ln -s "$DOTFILES/scripts/invoice.sh" "$HOME/.local/bin/invoice"

rm -rf "$HOME/.local/bin/video_label"
ln -s "$DOTFILES/scripts/video/label_video.sh" "$HOME/.local/bin/video_label"

rm -rf "$HOME/.local/bin/video_stack"
ln -s "$DOTFILES/scripts/video/stack_video.sh" "$HOME/.local/bin/video_stack"

rm -rf "$HOME/.local/bin/video_info"
ln -s "$DOTFILES/scripts/video/info_video.sh" "$HOME/.local/bin/video_info"

ln -sf "$DOTFILES/scripts/_invoice.sh" "$COMPLETION_DIR/_invoice"

rm -rf "$HOME/.local/bin/syncWork"
ln -s "$DOTFILES/scripts/syncWork.sh" "$HOME/.local/bin/syncWork"

rm -rf "$HOME/.local/bin/pdfshrink"
ln -s "$DOTFILES/scripts/pdfshrink.sh" "$HOME/.local/bin/pdfshrink"

rm -rf "$HOME/.local/bin/tmux_timew_status"
rm -rf "$HOME/.local/bin/tmux_timew_status_block"
ln -s "$DOTFILES/scripts/tmux_timew_status.sh" "$HOME/.local/bin/tmux_timew_status"
ln -s "$DOTFILES/scripts/tmux_timew_status_block.sh" "$HOME/.local/bin/tmux_timew_status_block"

rm -rf "$HOME/.local/bin/m"
ln -s "$DOTFILES/scripts/mycli_pass.sh" "$HOME/.local/bin/m"

# Aliases
rm -rf "$HOME/.aliases"
ln -s "$DOTFILES/.aliases" "$HOME/.aliases"

# Phpactor config
rm -rf "$HOME/.config/phpactor"
ln -s "$DOTFILES/phpactor" "$HOME/.config/phpactor"

# Zsh completion init
autoload -Uz compinit
compinit
